chore: Create maven.yml
vaadin/form-filler-demo pull request #3
Opened 2023-08-21 13:49 UTC by mshabarov

2023-08-21 14:03 UTC, manolo requested changes

2023-08-21 14:03 UTC, manolo commented on .github/workflows/maven.yml
> +    branches: [ "main" ]
remove this line, I think all PRs should be verified

2023-08-21 19:57 UTC, manolo commented
I fixed the problem with the TOKEN, System.property fails, thus passing it as env var, now the build runs the tests but one assertion failing

```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.148 s <<< FAILURE! - in com.example.application.FormFillerTextIT
Error:  com.example.application.FormFillerTextIT.formFill_chooseText1_fillsForm  Time elapsed: 18.028 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <05/04/2023 12:13:00> but was: <10/01/2023 00:00:00>
```

2023-08-22 06:15 UTC, czp13 approved these changes

2023-08-22 07:30 UTC, merged